wandb_version: 1

max_depth:
  desc: null
  value: 10
min_samples_leaf:
  desc: null
  value: 3
min_samples_split:
  desc: null
  value: 2
n_estimators:
  desc: null
  value: 12
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.3
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685950435.214906
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.11
      5: 0.15.3
      8:
      - 5
